#!/bin/bash

RED=$(tput setaf 1)
GREEN=$(tput setaf 2)
ORANGE=$(tput setaf 3)
BOLD=$(tput bold)
CLEAR=$(tput sgr0)

function warn { echo -en "\n\n${BOLD}${ORANGE}[-] $* ${CLEAR}\n"; }
function success { echo -en "${BOLD}${GREEN}[+] $* ${CLEAR}\n"; }
function info { echo -en "\n\n${BOLD}[ ] $* ${CLEAR}\n"; }
function error { echo -en "${BOLD}${RED}[!] $* ${CLEAR}\n"; }
function notify { echo -en "\n\n${BOLD}${ORANGE}[!] $* ${CLEAR}\n"; }

PACKAGES=(
    alacritty
    arc-gtk-theme
    dex
    dunst
    fakeroot
    feh
    flameshot
    fzf
    git
    gnome-keyring
    gpick
    i3lock
    imagemagick
    lxsession-gtk3
    make
    noto-fonts-emoji
    pacman-contrib
    patch
    picom
    pipewire
    pipewire-alsa
    pipewire-audio
    pipewire-docs
    pipewire-jack
    pipewire-pulse
    playerctl
    polybar
    python-pywal
    python-requests
    rofi
    trash-cli
    ttf-jetbrains-mono
    ttf-nerd-fonts-symbols
    which
    xss-lock
    zsh
    zsh-autosuggestions
    zsh-syntax-highlighting
)

gsettings set org.cinnamon.desktop.default-applications.terminal exec alacritty

if [[ $(yadm config --get local.class) == "" ]]; then
    notify "yadm - Class has not been set yet"
    echo -n "Enter Class: "
    read -r YADM_CLASS
    yadm config local.class "$YADM_CLASS"
fi

sudo pacman -S "${PACKAGES[@]}"


if ! type pikaur; then
    mkdir -p ~/.builds/
    wget \
        https://github.com/actionless/pikaur/archive/refs/tags/1.17.tar.gz \
        -O ~/.builds/pikaur.tar.gz
    cd ~/.builds || exit
    tar xfzv pikaur.tar.gz && cd ~/.builds/pikaur-* || exit
    makepkg -rsci
fi

